runtime: go119  # or another supported version

instance_class: F1

automatic_scaling:
  max_instances: 1

env_variables:
  TELEGRAM_WEBHOOK_URL: "smart-invest-337212.de.r.appspot.com"

inbound_services:
  - warmup

handlers:
- url: /_ah/warmup
  script: main.go
  login: admin